CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_number VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE accounts ADD CONSTRAINT uc_accounts_document_number UNIQUE (document_number);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL,
    operation_type INTEGER NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE transactions
    ADD CONSTRAINT fk_transactions_accounts
        FOREIGN KEY (account_id)
            REFERENCES accounts (id);